'''
Write a script to save your chat_history which was generated by your chatgpt api.

Every time we want to save the history, we will enter some key, and then it will save the conversation we had till now in db
'''
!pip install openai
!pip install gradio
!pip install mysql-connector
!pip install pyodbc

import openai
import mysql.connector
import datetime

openai.api_key = "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"

cnx = mysql.connector.connect(host="localhost",user="root",password="pcs123",database="mysql")
My_cursor = cnx.cursor()
My_cursor.execute("""CREATE TABLE IF NOT EXISTS TABLE (
                    USER VARCHAR(50) NOT NULL,
                    BOT VARCHAR(2500) NOT NULL,
                    Date DATE NOT NULL);""");


chat_history = []
while (1):
    feed = input("user: ")

    if (feed == "exit"):
        res = '\n'.join(chat_history)
        break

    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[{"role": "user", "content": feed}]
    )
    print("bot: "+response['choices'][0]['message']['content'])
    print()
    result = ""
    result += feed
    result += "\n"
    result += response['choices'][0]['message']['content']
    date = datetime.datetime.now();
    insert_into_sql = "INSERT INTO TABLE (USER,BOT,Date) VALUES (%s, %s, %s)"
    data_push = (feed,response['choices'][0]['message']['content'],date)
    My_cursor.execute(insert_into_sql, data_push)
    cnx.commit()
    chat_history.append(result)
